// <auto-generated />
namespace MvcMusicStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _1552 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1552));
        
        string IMigrationMetadata.Id
        {
            get { return "201406141753043_15-52"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
